name: Github pages Documentation

on:
  push:
    branches: [ main, master, feature/JB-6 ]

jobs:
  update_documentation:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.x' ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
        cache: 'pip'
    - run: pip install mkdocs mkdocs-material
    - name: Deploy github pages
      working-directory: ./documentation
      run: python -m mkdocs build --clean
    - name: Copy to gh-pages
        env:
          SRC_FOLDER_PATH: 'documentation/site'
          TARGET_BRANCH: 'gh-pages'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch